dist: bionic
services:
  - docker
  - xvfb

branches:
    only:
        - master

notifications:
  email: false

before_install:
  - docker pull quay.io/fenicsproject/stable:latest

script:
  - docker run -ti quay.io/fenicsproject/stable:latest python3 -c "import dolfin;print(dolfin.__version__)"
  # - docker run --rm -P -v `pwd`:/home/fenics/shared -w /home/fenics/shared quay.io/fenicsproject/stable:2017.2.0 "python3 -m pytest -v -k '_ci_'"

