# sudo: false
dist: bionic
services:
  - xvfb

language: python

python:
  - '3.7'

addons:
  apt:
    packages:

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda3.sh
  - chmod +x $HOME/miniconda3.sh
  - "$HOME/miniconda3.sh -b;"
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes -n base -c defaults conda
  - conda install --yes -c menpo vtk=8
  - conda install --yes -c anaconda pyqt
  - conda install --yes -c conda-forge fenics mshr gmsh pybind11 pip
  # https://lxml.de/installation.html
  - sudo apt-get install python3-lxml
  - sudo apt-get install libxml2-dev libxslt-dev python-dev
  - sudo apt-get build-dep python3-lxml
  - sudo apt-get install libhdf5-dev

install:
  # - conda install --yes -c conda-forge --file requirements.txt
  - conda list
  - pip install -r requirements.txt
  - pip install lxml codecov h5py
  - pip install --user travis-sphinx
  - export PATH=$HOME/.local/bin:$PATH

script:
  # https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  - py.test  --cov-report term --cov=.
#  - xvfb-run make test
  # https://gist.github.com/kemingy/7e715ceb1b96f8023bea89a82974a181
  # https://github.com/Syntaf/travis-sphinx
  - travis-sphinx build -n --source=docs/.

after_success:
  - travis-sphinx deploy
  - codecov
