sudo: false
dist: bionic

language: python

python:
  - '3.7'

addons:
  apt:
    packages:
      # - texlive-latex-recommended
      # - texlive-fonts-recommended
      # - texlive-latex-extra
      # - dvipng

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda3.sh
  - chmod +x $HOME/miniconda3.sh
  - "$HOME/miniconda3.sh -b;"
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes -n base -c defaults conda
  - conda install -c menpo vtk=7

install:
  # - conda install --yes -c conda-forge --file requirements.txt
  - conda create -n fenicsproject --yes -c conda-forge fenics mshr pybind11 pip
  - source activate fenicsproject
  - conda list
  - pip install -r requirements.txt
  - pip install travis-sphinx nose-timer

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python pack.py
#  - "./docs/update_apidocs.sh"
#  - nosetests -v --with-timer --with-coverage --cover-erase --cover-inclusive --cover-package=pySDC/core,pySDC/implementations,pySDC/helpers,pySDC/tutorial,pySDC/projects --cover-html --cover-html-dir=doc/build/test_coverage pySDC/tests
#  - travis-sphinx build

#after_success:
#  - travis-sphinx deploy